### ISSUE TITLE
convert is not a function

### ISSUE THREAD

**Issue by joezappie** [calebdwilliams/rollup-plugin-import-assert#7]
I'm trying to use this with vite to assert css imports. When running it though I'm getting an error:

```
1:12:46 AM [vite] Internal server error: convert is not a function
  Plugin: rollup-plugin-import-assert
  File: /workspaces/mrp/app/components/zy/input.css
      at TransformContext.transform (file:///workspaces/mrp/node_modules/rollup-plugin-import-assert/dist/import-assert.js:83:73)
      at Object.transform (file:///workspaces/mrp/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:35290:53)
      at async loadAndTransform (file:///workspaces/mrp/node_modules/vite/dist/node/chunks/dep-5cb728cb.js:39869:29)
```

Logging convert its an object with default: `{ default: [Function: convert] }`

Looking at the version of `string-to-template-literal` that is used, its `0.2.2`. There is also a version `2.0.0`. If I switch this plugin to use `2.0.0` it loads fine. Is there a reason an older version is being used?

**Comment by calebdwilliams** [comment]
Fixed in 3.0.1
